[package]
name = "clipr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = "1.4.9"
scrap = "0.5.0"
repng = "0.2.2"